language: go

go:
  - "1.16"

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-linux.zip -O ninja-1.10.2.zip
  - sudo unzip ninja-1.10.2.zip -d /usr/local/bin
  - sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

script:
  - go build ./build/cmd/bood
  - sudo mv bood /usr/local/bin/
  - cd build
  - bood
  - echo "TEST RESULTS:"
  - find ./out/reports/ -type f -print -exec cat {} \;
  - echo "DOCS:"
  - cat out/docs/my-docs.txt
  - cd ../examples
  # go to each example subdirectory and execute bood
  - find -mindepth 1 -maxdepth 1 -type d -exec bash -c 'echo "RUNNING ${1#./}"; cd ${1#./} && bood' -- '{}' \;

deploy:
  provider: releases
  api_key: $OAUTH_TOKEN
  file: "/usr/local/bin/bood"
  skip_cleanup: true
  on:
    tags: true
