language: go

go:
  - "1.16"

before_install:
  - wget https://github.com/ninja-build/ninja/archive/v1.7.0.zip -O ninja-1.7.0.zip
  - sudo unzip ninja-1.7.0.zip -d /usr/local/bin
  - sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force

script:
  - go build ./build/cmd/bood
  - cd build
  - ../bood